# Generated by Django 3.2.2 on 2021-05-18 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=50, unique=True, verbose_name='Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_type_char', models.CharField(max_length=15, unique=True, verbose_name='Key')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_char', models.CharField(max_length=50, unique=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='TuneType',
            fields=[
                ('tune_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('tune_type_char', models.CharField(max_length=50, unique=True, verbose_name='Tune Type')),
            ],
        ),
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('tune_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Tune Name')),
                ('parts', models.IntegerField(verbose_name='Number of Parts in Tune')),
                ('tune_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosession.tunetype', verbose_name='Tune Type')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='Recording URL')),
                ('date_recorded', models.DateField(blank=True, null=True)),
                ('bpm', models.IntegerField(verbose_name='Beats Per Minute of Recording')),
                ('beats_space', models.IntegerField(verbose_name='Beats Before Count-In')),
                ('beats_countin', models.IntegerField(verbose_name='Beats That Are Count In Before Tune Plays')),
                ('beats_ending', models.IntegerField(verbose_name='Beats After Tune Stops Playing')),
                ('repeats', models.IntegerField(verbose_name='Number of Repeats of Tune On Recording')),
                ('pickup_beats', models.FloatField(verbose_name='Number of Pick Up Beats Into First Beat of First A Part')),
                ('bpm_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosession.note', verbose_name='BPM Note')),
                ('insturment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosession.instrument', verbose_name='Instrument used during recording')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosession.key', verbose_name='Key of Tune')),
                ('tune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosession.tune', verbose_name='Tune')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recording_id'],
            },
        ),
    ]
